services:
  app:
    # image: dogfetus/mal-tui:latest 
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    container_name: mal-tui
    restart: unless-stopped


networks:
  default:
    external: true
    name: public
